# ------------------- General Options -------------------------
description: AB3DMOT        # 跟踪器名称或描述
seed: 0                     # 随机种子，保证结果可复现

# --------------- main.py 部分（数据集相关配置）
save_root: ./results/ROS    # 保存结果路径，可以改成ROS专用目录
dataset: KITTI                # 数据集名称，这里用ROS表示实时数据流
split: val                  # 保留字段，随便填 val/test 都行
det_name: pvrcnn         # 检测器名称，改成你ROS节点的名字
cat_list: ['Car', 'Pedestrian', 'Cyclist']  # 跟踪类别

score_threshold: -10000     # 分数阈值，默认不过滤
num_hypo: 1                 # 多假设数量

# --------------- model.py 部分（跟踪器配置）
ego_com: true              # 是否启用自车运动补偿（ROS场景通常关闭）
vis: false                  # 是否开启可视化（开启会降低速度）
affi_pro: true              # 是否启用关联概率
min_hits: 3                 # 最少连续命中次数
max_age: 10                # 最大跟踪寿命（帧数）
match_algorithm: hungarian  # 匹配算法，可选 hungarian / greedy
